networks:
  frontend:
    external: true
    name: reverse-proxy
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  db:
    image: mariadb:10.11
    restart: ${RESTART}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database_volume:/var/lib/mysql
      - ./backups:/backups
    networks:
      - backend

  mailhog:
    build: ./docker/mailhog
    expose:
      - 8025
      - 1025
    networks:
      - frontend
      - backend
    labels:
      # enable traefik
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      # http
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.passbolt.localhost`)"
      - "traefik.http.routers.mailhog.entrypoints=web"

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: ${RESTART}
    depends_on:
      - db
      - mailhog
    environment:
      APP_FULL_BASE_URL: http://${DOMAIN}
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: ${DB_USER}
      DATASOURCES_DEFAULT_PASSWORD: ${DB_PASSWORD}
      DATASOURCES_DEFAULT_DATABASE: ${DB_DATABASE}
      EMAIL_DEFAULT_FROM_NAME: ${MAIL_FROM_NAME}
      EMAIL_DEFAULT_FROM: ${MAIL_FROM}
      EMAIL_TRANSPORT_DEFAULT_HOST: ${MAIL_HOST}
      EMAIL_TRANSPORT_DEFAULT_PORT: ${MAIL_PORT}
      EMAIL_TRANSPORT_DEFAULT_USERNAME: ${MAIL_USER}
      EMAIL_TRANSPORT_DEFAULT_PASSWORD: ${MAIL_PASSWORT}
      EMAIL_TRANSPORT_DEFAULT_TLS: ${MAIL_TLS}
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    # ports:
    #   - 80:80
    #   - 443:443
    #Alternatively for non-root images:
    # - 80:8080
    # - 443:4433
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # http
      - "traefik.http.routers.passbolt.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.passbolt.entrypoints=web"


volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
